### ISSUE TITLE
Логическая ошибка при записи к врачу

### ISSUE THREAD

**Issue by PrudyvusP** [web-search-for-the-nearest-hospitals/backend#112]
Нынешней логикой записи к врачу установлено, что мы создаем пользователя против его воли при создании записи к врачу. Тем временем, регистрация и аутентификация пользователя происходит по паре "почта-пароль", при этом почта - уникальная. Таким образом, в настоящее время, неавторизованный пользователь, записавшийся к врачу, не сможет пройти регистрацию в сервисе, так как его почта уже занята, а пароль к учетке не установлен.

```python
        with transaction.atomic():
            instance = get_object_or_404(
                Appointment
                .objects
                .only('id', 'status')
                .select_for_update(), pk=kwargs.get('pk')
            )
            if instance.status != Appointment.FREE:
                return response.Response(
                    status=http.HTTPStatus.BAD_REQUEST,
                    data={"detail": "Этот талон уже занят"})

            # Создание пользователя здесь - это следствие неуспеваемости других команд

            user, _ = (
                User
                .objects
                .only('id')
                .get_or_create(email=data.get('email'))
            )
            user.last_name = last_name
            user.first_name = first_name
            user.third_name = third_name
            user.phone = data.get('phone')
            user.save(
                update_fields=['last_name', 'first_name',
                               'third_name', 'phone']
            )

            instance.client, instance.status = user, Appointment.PLANNED
            instance.save(update_fields=['client', 'status'])
```

Решение этой проблемы в лоб - удалить создание пользователя при записи к врачу
Решение красивое еще не придумано

**Comment by PavlovMaximYurevich** [comment]
А можно ли избавиться от емейла на данном этапе? Или здесь юзер не получит сведений на почту об успешной записи и т.д.? В лоб решение можно немного улучшить - например, удалить емейл, а не целого юзера, но пока мне такое решение тоже не особо нравится. Подумаю на досуге еще..

**Comment by PrudyvusP** [comment]
> А можно ли избавиться от емейла на данном этапе? Или здесь юзер не получит сведений на почту об успешной записи и т.д.? В лоб решение можно немного улучшить - например, удалить емейл, а не целого юзера, но пока мне такое решение тоже не особо нравится. Подумаю на досуге еще..

Неа, электронная почта должна по-любому отображраться для представителя больнички (чтобы он мог понять, кто записался хотя бы по почте), сейчас эта вся инфа упакована через связь с пользователями под названием "Клиент"
![Screenshot 2024-01-17 at 15-04-12 Добавить Запись пациента на прием Административный сайт Django](https://github.com/web-search-for-the-nearest-hospitals/backend/assets/67255606/def46bd5-9668-42eb-aa28-0621279dfd1a)
В лоб способ имелся в виду, что вместо "клиента" сделать тупо почту, телефон и email пользователя)

**Comment by PrudyvusP** [comment]
Эта ручка будет достунпа только авторизованным пользователям, поэтому поведение будет исправлено
