### ISSUE TITLE
Документация ручки отзывов

### ISSUE THREAD

**Issue by PrudyvusP** [web-search-for-the-nearest-hospitals/backend#139]
Openapi 
POST & GET (LIST)

**Comment by SvetlanaKrut** [comment]
То есть чтения, обновления и удаления отзыва не будет?

**Comment by PrudyvusP** [comment]
> То есть чтения, обновления и удаления отзыва не будет?

Хороший вопрос. Учитывая, что этого нет на стороне дизайна и на стороне фронта, будет странно делать на бэке (организацию уже сделали в таком же ключе)
