### ISSUE TITLE
Доменное имя проекта

### ISSUE THREAD

**Issue by PrudyvusP** [web-search-for-the-nearest-hospitals/backend#34]
Необходимо настроить доменное имя проекта, в дальнешем здесь появится наименование)

**Comment by KseniaBregadze** [comment]
Павел, может тогда зарегистрируем PoisKlinik? Вроде в чате обсуждали, что можно его. Мне кажется, что должно быть достаточно простое и перекликающееся с названием, сильно извращаться не нужно

**Comment by PrudyvusP** [comment]
@KseniaBregadze Ксения, если Вы даете зеленый цвет как PR, мы делаем)
если все проголосовали, то можно подвести итоги и закрепить их результаты)

**Comment by PrudyvusP** [comment]
кусок нашего доменного имени - poisklinik. 
по идее должно получиться что-то poisklinik.rofel.ru
rofel.ru - нам дают эту строчку
мы испольузем домен третьего уровня.

**Comment by PrudyvusP** [comment]
Сервис доступен по адресу http://poisklinik.acceleratorpracticum.ru/api/
От души)
